Normalization from example_ynh

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -37,8 +37,6 @@ test ! -e "$final_path" || ynh_die "This path already contains a folder"
 # Normalize the url path syntax
 path_url=$(ynh_normalize_url_path $path_url)
 
-# Check web path availability
-ynh_webpath_available $domain $path_url
 # Register (book) web path
 ynh_webpath_register $app $domain $path_url
 
@@ -89,15 +87,10 @@ ynh_setup_source "$final_path"
 #=================================================
 
 # Do not serve .well-known if it's already served on the domain
-if is_url_handled "https://${domain}/.well-known/caldav" ; then
+if is_url_handled "https://$domain/.well-known/caldav" ; then
     sed -ri '/^location = \/\.well\-known\/(caldav|carddav) \{/,/\}/d' \
-	"../conf/nginx.conf"
+        "../conf/nginx.conf"
 fi
-
-# Handle root path, avoid double slash.
-# Temporary fix, in waiting for an upgrade of the helper. (#361)
-path_url_slash_less=${path_url%/}
-ynh_replace_string "__PATH__/" "$path_url_slash_less/" "../conf/nginx.conf"
 
 # Create a dedicated nginx config
 ynh_add_nginx_config
@@ -123,7 +116,7 @@ ynh_add_fpm_config
 #=================================================
 
 # Define app's data directory
-datadir="/home/yunohost.app/${app}/data"
+datadir="/home/yunohost.app/$app/data"
 # Create app folders
 mkdir -p "$datadir"
 
@@ -131,16 +124,22 @@ mkdir -p "$datadir"
 # INSTALL NEXTCLOUD
 #=================================================
 
+# Define a function to execute commands with `occ`
+exec_occ() {
+  (cd "$final_path" && exec_as "$app" \
+      php occ --no-interaction --no-ansi "$@")
+}
+
 # Set write access for the following commands
 chown -R $app: "$final_path" "$datadir"
 
 # Install Nextcloud using a temporary admin user
 exec_occ maintenance:install \
-    --database "mysql" --database-name "$db_name" \
-    --database-user "$db_name" --database-pass "$db_pwd" \
+    --database "mysql" --database-name $db_name \
+    --database-user $db_name --database-pass "$db_pwd" \
     --admin-user "admin" --admin-pass "$(ynh_string_random 6)" \
     --data-dir "$datadir" \
-  || ynh_die "Unable to install Nextcloud"
+    || ynh_die "Unable to install Nextcloud"
 
 #=================================================
 # CONFIGURE NEXTCLOUD
@@ -149,24 +148,28 @@ exec_occ maintenance:install \
 # Ensure that UpdateNotification app is disabled
 exec_occ app:disable updatenotification
 
-# Enable plugins
+# Enable ldap plugins
 exec_occ app:enable user_ldap
 exec_occ ldap:create-empty-config
 
 # Load the installation config file in nextcloud
-nc_conf="${final_path}/config_install.json"
+nc_conf="$final_path/config_install.json"
 cp ../conf/config_install.json "$nc_conf"
-ynh_replace_string "#DOMAIN#" "$domain" "$nc_conf"
-ynh_replace_string "#DATADIR#" "$datadir" "$nc_conf"
+
+ynh_replace_string "__DOMAIN__" "$domain" "$nc_conf"
+ynh_replace_string "__DATADIR__" "$datadir" "$nc_conf"
 exec_occ config:import "$nc_conf"
-# Then remove it
+
+# Then remove the config file
 rm -f "$nc_conf"
 
 # Load the additional config file (used also for upgrade)
-nc_conf="${final_path}/config_install.json"
+nc_conf="$final_path/config.json"
 cp ../conf/config.json "$nc_conf"
+
 exec_occ config:import "$nc_conf"
-# Then remove it
+
+# Then remove the config file
 rm -f "$nc_conf"
 
 #=================================================
@@ -181,13 +184,26 @@ exec_occ ldap:test-config \'\' \
 # MOUNT HOME FOLDERS AS EXTERNAL STORAGE
 #=================================================
 
+# Define a function to add an external storage
+# Create the external storage for the given folders and enable sharing
+create_external_storage() {
+  local datadir="$1"
+  local mount_name="$2"
+  local mount_id=`exec_occ files_external:create --output=json \
+      "$mount_name" 'local' 'null::null' -c "datadir=$datadir" || true`
+  ! [[ $mount_id =~ ^[0-9]+$ ]] \
+      && echo "Unable to create external storage" >&2 \
+      || exec_occ files_external:option "$mount_id" enable_sharing true
+}
+
 # Enable External Storage and create local mount to home folder
-if [ $user_home -eq 1 ]; then
+if [ $user_home -eq 1 ]
+then
     exec_occ app:enable files_external
     create_external_storage "/home/\$user" "Home"
     # Iterate over users to extend their home folder permissions
     for u in $(ynh_user_list); do
-        setfacl -m g:$app:rwx "/home/$u" || true
+        setfacl --modify g:$app:rwx "/home/$u" || true
     done
 fi
 
@@ -203,7 +219,7 @@ exec_occ config:system:get logout_url >/dev/null 2>&1 \
 \$main_domain = exec('cat /etc/yunohost/current_host');
 \$CONFIG['logout_url'] = 'https://'.\$main_domain.'/yunohost/sso/?action=logout';
 //-YunoHost-
-" >> "${final_path}/config/config.php"
+" >> "$final_path/config/config.php"
 
 #=================================================
 # REMOVE THE TEMPORARY ADMIN AND SET THE TRUE ONE
@@ -220,7 +236,7 @@ exec_occ user:delete admin
 #=================================================
 
 # Calculate and store the config file checksum into the app settings
-ynh_store_file_checksum "${final_path}/config/config.php"
+ynh_store_file_checksum "$final_path/config/config.php"
 
 #=================================================
 # ADD A CRON JOB
@@ -231,14 +247,15 @@ cp -a ../conf/nextcloud.cron "$cron_path"
 chown root: "$cron_path"
 chmod 644 "$cron_path"
 
-ynh_replace_string "#USER#" "$app" "$cron_path"
-ynh_replace_string "#DESTDIR#" "$final_path" "$cron_path"
+ynh_replace_string "__USER__" "$app" "$cron_path"
+ynh_replace_string "__DESTDIR__" "$final_path" "$cron_path"
 
 exec_occ background:cron
 
 #=================================================
 # POST-INSTALL MAINTENANCE
 #=================================================
+
 (cd /tmp ; at now + 10 minutes <<< "(cd $final_path ; sudo -u $app php occ db:add-missing-indices ; sudo -u $app php occ db:convert-filecache-bigint -n) > /tmp/${app}_maintenance.log")
 
 #=================================================
@@ -246,7 +263,7 @@ exec_occ background:cron
 #=================================================
 
 # Set system group in hooks
-ynh_replace_string "#GROUP#" "$app" ../hooks/post_user_create
+ynh_replace_string "__GROUP__" "$app" ../hooks/post_user_create
 
 #=================================================
 # YUNOHOST MULTIMEDIA INTEGRATION
@@ -269,19 +286,19 @@ ynh_multimedia_addaccess $app
 
 # Fix app ownerships & permissions
 chown -R $app: "$final_path" "$datadir"
-find ${final_path}/ -type f -print0 | xargs -0 chmod 0644
-find ${final_path}/ -type d -print0 | xargs -0 chmod 0755
-find ${datadir}/ -type f -print0 | xargs -0 chmod 0640
-find ${datadir}/ -type d -print0 | xargs -0 chmod 0750
-chmod 640 "${final_path}/config/config.php"
+find $final_path/ -type f -print0 | xargs -0 chmod 0644
+find $final_path/ -type d -print0 | xargs -0 chmod 0755
+find $datadir/ -type f -print0 | xargs -0 chmod 0640
+find $datadir/ -type d -print0 | xargs -0 chmod 0750
+chmod 640 "$final_path/config/config.php"
 chmod 755 /home/yunohost.app
 
 #=================================================
 # SETUP LOGROTATE
 #=================================================
 
-# Use logrotate to manage application logfile
-ynh_use_logrotate "${datadir}/nextcloud.log"
+# Use logrotate to manage application logfile(s)
+ynh_use_logrotate "$datadir/nextcloud.log"
 
 #=================================================
 # SETUP SSOWAT
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -38,34 +38,33 @@ if [ -z $final_path ]; then
 	ynh_app_setting_set $app final_path $final_path
 fi
 
+# Remove the option backup_core_only if it's in the settings.yml file
+ynh_app_setting_delete $app backup_core_only
+
 #=================================================
 # BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
 #=================================================
 
 # Made a backup only after the version 11.0.0
 # Before, the datas will be always saved.
-
 # Get the current version number of nextcloud/owncloud
 current_version=$(grep OC_VersionString "$final_path/version.php" | cut -d\' -f2)
 current_major_version=${current_version%%.*}
 
 if [ $current_major_version -gt 11 ]
 then
-    # Inform the backup/restore process that it should not save the data directory
-    ynh_app_setting_set $app backup_core_only 1
-
     # Backup the current version of the app
     ynh_backup_before_upgrade
     ynh_clean_setup () {
-	# Remove the post migration script before its execution !
-	ynh_secure_remove "/tmp/owncloud_post_migration.sh" 2>&1
+		# Remove the post migration script before its execution !
+		ynh_secure_remove "/tmp/owncloud_post_migration.sh" 2>&1
 
-	# restore it if the upgrade fails
-	ynh_restore_upgradebackup
+		# restore it if the upgrade fails
+		ynh_restore_upgradebackup
     }
 fi
 
-# Exit if an error occurs during the script execution
+# Exit if an error occurs during the execution of the script
 ynh_abort_if_errors
 
 #=================================================
@@ -75,7 +74,7 @@ ynh_abort_if_errors
 ynh_handle_app_migration "owncloud" "owncloud_migration"
 if [ $migration_process -eq 1 ]
 then
-    # If a migration has been perform
+    # If a migration has been performed
     # Reload some values changed by the migration process
     final_path=$(ynh_app_setting_get $app final_path)
     db_name=$(ynh_app_setting_get $app db_name)
@@ -106,19 +105,17 @@ path_url=$(ynh_normalize_url_path $path_url)
 # NGINX CONFIGURATION
 #=================================================
 
+ynh_backup_if_checksum_is_different "/etc/nginx/conf.d/$domain.d/$app.conf"
+
 # Delete current nginx configuration to be able to check if .well-known is already served.
 ynh_remove_nginx_config
 ynh_app_setting_delete $app "checksum__etc_nginx_conf.d_$domain.d_$app.conf" || true
-# Do not serve .well-known if it's already served on the domain
-if is_url_handled "https://${domain}/.well-known/caldav" ; then
-    sed -ri '/^location = \/\.well\-known\/(caldav|carddav) \{/,/\}/d' \
-	"../conf/nginx.conf"
-fi
 
-# Handle root path, avoid double slash.
-# Temporary fix, in waiting for an upgrade of the helper. (#361)
-path_url_slash_less=${path_url%/}
-ynh_replace_string "__PATH__/" "$path_url_slash_less/" "../conf/nginx.conf"
+# Do not serve .well-known if it's already served on the domain
+if is_url_handled "https://$domain/.well-known/caldav" ; then
+    sed -ri '/^location = \/\.well\-known\/(caldav|carddav) \{/,/\}/d' \
+        "../conf/nginx.conf"
+fi
 
 # Create a dedicated nginx config
 ynh_add_nginx_config
@@ -127,7 +124,7 @@ ynh_add_nginx_config
 # CREATE DEDICATED USER
 #=================================================
 
-# Create a system user
+# Create a dedicated user (if not existing)
 ynh_system_user_create $app
 
 #=================================================
@@ -149,13 +146,20 @@ ynh_install_app_dependencies $pkg_dependencies
 # MAKE SEQUENTIAL UPGRADES FROM EACH MAJOR
 # VERSION TO THE NEXT ONE
 #=================================================
+ynh_print_info "Upgrading nextcloud..."
+
+# Define a function to execute commands with `occ`
+exec_occ() {
+  (cd "$final_path" && exec_as "$app" \
+      php occ --no-interaction --no-ansi "$@")
+}
 
 # Load the last available version
 source upgrade.d/upgrade.last.sh
 last_version=$next_version
 
 # Define app's data directory
-datadir="/home/yunohost.app/${app}/data"
+datadir="/home/yunohost.app/$app/data"
 
 # Set write access for the following commands
 chown -R $app: "$final_path" "$datadir"
@@ -183,7 +187,7 @@ do
     # Load the value for this version
     source upgrade.d/upgrade.$current_major_version.sh
 
-    echo -e "\nUpgrade to nextcloud $next_version" >&2
+    ynh_print_info "Upgrade to nextcloud $next_version"
 
     # Create an app.src for this version of nextcloud
     cp ../conf/app.src.default ../conf/app.src
@@ -217,7 +221,7 @@ do
     # Upgrade Nextcloud (SUCCESS = 0, UP_TO_DATE = 3)
     exec_occ maintenance:mode --off
     exec_occ upgrade \
-      || ([[ $? -eq 3 ]] || ynh_die "Unable to upgrade Nextcloud")
+      || ([ $? -eq 3 ] || ynh_die "Unable to upgrade Nextcloud")
 
     # Get the new current version number
     current_version=$(grep OC_VersionString "$final_path/version.php" | cut -d\' -f2)
@@ -232,12 +236,13 @@ done
 #=================================================
 
 # Verify the checksum and backup the file if it's different
-ynh_backup_if_checksum_is_different "${final_path}/config/config.php"
+ynh_backup_if_checksum_is_different "$final_path/config/config.php"
 
 nc_conf="${final_path}/config.json"
 cp ../conf/config.json "$nc_conf"
-ynh_replace_string "#DOMAIN#" "$domain" "$nc_conf"
-ynh_replace_string "#DATADIR#" "$datadir" "$nc_conf"
+
+ynh_replace_string "__DOMAIN__" "$domain" "$nc_conf"
+ynh_replace_string "__DATADIR__" "$datadir" "$nc_conf"
 
 # Ensure that UpdateNotification app is disabled
 exec_occ app:disable updatenotification
@@ -247,7 +252,8 @@ exec_occ app:enable user_ldap
 
 # Load the config file in nextcloud
 exec_occ config:import "$nc_conf"
-# Then remove it
+
+# Then remove the config file
 rm -f "$nc_conf"
 
 #=================================================
@@ -262,11 +268,23 @@ exec_occ config:system:get logout_url >/dev/null 2>&1 \
 \$main_domain = exec('cat /etc/yunohost/current_host');
 \$CONFIG['logout_url'] = 'https://'.\$main_domain.'/yunohost/sso/?action=logout';
 //-YunoHost-
-" >> "${final_path}/config/config.php"
+" >> "$final_path/config/config.php"
 
 #=================================================
 # MOUNT HOME FOLDERS AS EXTERNAL STORAGE
 #=================================================
+
+# Define a function to add an external storage
+# Create the external storage for the given folders and enable sharing
+create_external_storage() {
+  local datadir="$1"
+  local mount_name="$2"
+  local mount_id=`exec_occ files_external:create --output=json \
+      "$mount_name" 'local' 'null::null' -c "datadir=$datadir" || true`
+  ! [[ $mount_id =~ ^[0-9]+$ ]] \
+      && echo "Unable to create external storage" >&2 \
+      || exec_occ files_external:option "$mount_id" enable_sharing true
+}
 
 # Enable External Storage and create local mount to home folder as needed
 if [ $user_home -eq 1 ]; then
@@ -276,7 +294,7 @@ if [ $user_home -eq 1 ]; then
 	|| create_external_storage "/home/\$user" "Home"
     # Iterate over users to extend their home folder permissions
     for u in $(ynh_user_list); do
-      setfacl -m g:$app:rwx "/home/$u" || true
+      setfacl --modify g:$app:rwx "/home/$u" || true
     done
 fi
 
@@ -296,8 +314,8 @@ cp -a ../conf/nextcloud.cron "$cron_path"
 chown root: "$cron_path"
 chmod 644 "$cron_path"
 
-ynh_replace_string "#USER#" "$app" "$cron_path"
-ynh_replace_string "#DESTDIR#" "$final_path" "$cron_path"
+ynh_replace_string "__USER__" "$app" "$cron_path"
+ynh_replace_string "__DESTDIR__" "$final_path" "$cron_path"
 
 exec_occ background:cron
 
@@ -306,7 +324,7 @@ exec_occ background:cron
 #=================================================
 
 # Set system group in hooks
-ynh_replace_string "#GROUP#" "$app" ../hooks/post_user_create
+ynh_replace_string "__GROUP__" "$app" ../hooks/post_user_create
 
 #=================================================
 # YUNOHOST MULTIMEDIA INTEGRATION
@@ -329,11 +347,11 @@ ynh_multimedia_addaccess $app
 
 # Fix app ownerships & permissions
 chown -R $app: "$final_path" "$datadir"
-find ${final_path}/ -type f -print0 | xargs -0 chmod 0644
-find ${final_path}/ -type d -print0 | xargs -0 chmod 0755
-find ${datadir}/ -type f -print0 | xargs -0 chmod 0640
-find ${datadir}/ -type d -print0 | xargs -0 chmod 0750
-chmod 640 "${final_path}/config/config.php"
+find $final_path/ -type f -print0 | xargs -0 chmod 0644
+find $final_path/ -type d -print0 | xargs -0 chmod 0755
+find $datadir/ -type f -print0 | xargs -0 chmod 0640
+find $datadir/ -type d -print0 | xargs -0 chmod 0750
+chmod 640 "$final_path/config/config.php"
 chmod 755 /home/yunohost.app
 
 #=================================================
@@ -341,8 +359,8 @@ chmod 755 /home/yunohost.app
 #=================================================
 
 # Warn about possible disabled apps
-echo "Note that if you've installed some third-parties Nextcloud applications, \
-they are probably disabled and you'll have to manually enable them again." >&2
+ynh_print_warn "Note that if you've installed some third-parties Nextcloud applications, \
+they are probably disabled and you'll have to manually enable them again."
 
 #=================================================
 # SETUP LOGROTATE
@@ -373,10 +391,10 @@ systemctl reload nginx
 
 if [ $migration_process -eq 1 ]
 then
-    echo "ownCloud has been successfully migrated to Nextcloud! \
+    ynh_print_info "ownCloud has been successfully migrated to Nextcloud! \
 A last scheduled operation will run in a couple of minutes to finish the \
 migration in YunoHost side. Do not proceed any application operation while \
-you don't see Nextcloud as installed." >&2
+you don't see Nextcloud as installed."
 
     # Execute a post migration script after the end of this upgrade.
     # Mainly for some cleaning
