Update upgrade

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -45,7 +45,7 @@ then
     version_to_follow=stable
     ynh_app_setting_set --app=$app --key=version_to_follow --value="$version_to_follow"
 fi
-
+    
 
 #=================================================
 # SPECIFIC UPGRADE
@@ -132,6 +132,11 @@ current_major_version=${current_version%%.*}
 
 last_version=$(ynh_read_manifest --manifest_key="resources.sources.main.url" | grep -o '[0-9][0-9]\.[0-9]\.[0-9][0-9]')
 last_major_version=${last_version%%.*}
+if [[ "$version_to_follow" == "oldstable" ]]
+then
+    last_major_version=$(( $last_major_version - 1 ))
+    last_version=$(ynh_read_manifest --manifest_key="resources.sources.${last_major_version}.url" | grep -o '[0-9][0-9]\.[0-9]\.[0-9]')
+fi
 
 if [[ "$last_major_version" != "$current_major_version" ]]
 then
@@ -173,17 +178,20 @@ then
     fi
 
     # While the current version is not the last version, do an upgrade
-    while [ "$last_version" != "$current_version" ]
+    while [[ "$last_version" > "$current_version" ]]
     do
 
         next_major_version="$(( $current_major_version + 1 ))"
+        source_id="$next_major_version"
         if [[ "$next_major_version" -ge "$last_major_version" ]]; then
             ynh_print_info --message="Upgrading to Nextcloud $last_version"
             cp -a ../sources/patches_last_version/* ../sources/patches
-            source_id="main"
+            if [[ "$version_to_follow" != "oldstable" ]]
+            then
+                source_id="main"
+            fi
         else
             ynh_print_info --message="Upgrading to Nextcloud $next_major_version"
-            source_id="$next_major_version"
         fi
 
         # Create a temporary directory
@@ -363,6 +371,8 @@ ynh_app_setting_delete --app=$app --key="checksum__etc_nginx_conf.d_$domain.d_$a
 # Wait untils NGINX has fully reloaded
 ynh_systemd_action --service_name=nginx --action=reload --line_match="Reloaded" --log_path="systemd"
 
+wait_nginx_reload
+
 # Check if .well-known is available for this domain
 if is_url_handled --domain="$domain" --path="/.well-known/caldav" || is_url_handled --domain="$domain" --path="/.well-known/carddav"
 then
@@ -373,7 +383,44 @@ then
 fi
 
 # Create a dedicated NGINX config
+nginx_extra_conf_dir="/etc/nginx/conf.d/$domain.d/$app.d"
+mkdir -p "$nginx_extra_conf_dir"
+
+if [ $enable_notify_push -eq 1 ]
+then
+    ynh_add_config --template="notify_push.conf" --destination="$nginx_extra_conf_dir/notify_push.conf"
+fi
+
+# Create a dedicated NGINX config
 ynh_add_nginx_config
+
+#=================================================
+# CONFIGURE NOTIFY_PUSH APP
+#=================================================
+
+if [ $enable_notify_push -eq 1 ]
+then
+    # If notify_push is disabled, reenable it
+    if exec_occ app:list | awk '/Disabled/{f=1;next} f' | grep -q -w notify_push; then
+        exec_occ app:enable notify_push
+    # If notify_push is not installed, install it
+    elif ! exec_occ app:list | awk '/Enabled/{f=1;next} /Disabled/{f=0} f' | grep -q -w notify_push; then
+        exec_occ app:install notify_push
+    fi
+    exec_occ config:app:set notify_push base_endpoint --value https://$domain${path_url%/}/push
+
+    case $YNH_ARCH in
+        amd64) arch="x86_64";;
+        arm64) arch="aarch64";;
+        armel|armhf) arch="armv7";;
+    esac
+
+    ynh_add_config --template="watcher.path" --destination="/etc/systemd/system/${app}-notify-push-watcher.path"
+    ynh_add_systemd_config --service="${app}-notify-push-watcher" --template="watcher.service"
+    systemctl enable --now ${app}-notify-push-watcher.path
+    ynh_add_systemd_config --service="${app}-notify-push"
+fi
+
 
 #=================================================
 # CRON JOB
@@ -398,6 +445,28 @@ ynh_use_logrotate --non-append
 
 # Create a dedicated Fail2Ban config
 ynh_add_fail2ban_config --logpath="/var/log/$app/nextcloud.log" --failregex="^.*Login failed: '.*' \(Remote IP: '<HOST>'.*$" --max_retry=5
+
+#=================================================
+# CHECK IF NOTIFY_PUSH WORKS
+#=================================================
+
+if [ $enable_notify_push -eq 1 ]
+then
+    count=0
+    # cron can sometimes fail when the database is not fully initialized, hence it's retried several times, see https://github.com/YunoHost-Apps/nextcloud_ynh/pull/720
+    while ! ynh_exec_as "$app" php${phpversion} --define apc.enable_cli=1 $install_dir/cron.php && [[ $count -lt 30 ]]
+    do
+        sleep 1
+        count=$((count + 1))
+    done
+
+    ynh_systemd_action --service_name="${app}-notify-push-watcher" --action=restart
+    ynh_systemd_action --service_name="${app}-notify-push" --action=restart --line_match="Push daemon for Nextcloud clients." --log_path="systemd" --action=restart
+
+    if ! exec_occ notify_push:self-test; then
+        ynh_print_warn --message="The High Performance Backend service is still not working properly. Please log in with a user to your NextCloud instance, restart the High Performance Backend service with \"systemctl restart ${app}-notify-push.service\", and run \"sudo -u $app php${phpversion} $install_dir/occ notify_push:self-test\" to verify that everything is green."
+    fi
+fi
 
 #=================================================
 # END OF SCRIPT
